Alias ::= 'Cmnd_Alias' Cmnd_Alias (':' Cmnd_Alias)*

NAME ::= #'[A-Z]([A-Z]|[0-9]|\_)*'

Cmnd_Alias ::= NAME '=' Cmnd_List  |  NAME '=' '\\' '\n' Cmnd_List

file     ::= #'(/[a-zA-Z0-9_-]+)+'

wildcard ::= #'\?|\*|\+'

flag = #'\-[a-z]'

directory ::= #'(/[a-zA-Z0-9_-]+)+/(\?|\*|\+)?'

args = (wildcard | flag)+

commandname ::= file |
                file args |
                file args '""'

Cmnd_List ::= (Cmnd | Cmnd ',' | Cmnd {','} '\\')+

Cmnd ::= '!'* commandname |
          '!'* directory |
          '!'* "sudoedit" |
          '!'* Cmnd_Alias
